Feat/#8: Image 컴포넌트 구현
GDSC-PKNU-21-22/pknu-notice pull request #16
Opened 2023-03-21 08:36 UTC by hwinkr

## 🤠 개요

- #8 
- `Image` 컴포넌트 구현 및 `@types/node` 사용을 위한 의존성 추가,  `@asset` 절대 경로 설정

## 💫 설명

* Image 컴포넌트
  -  Image 컴포넌트를 구현 했어요.
  ```typescript
  const Image = ({ src, outline = false, size = 'medium' }: ImageProps) => {
    return (
      <StyledImage src={src} alt="" outline={outline} {...imageSize[size]} />
    );
  };
  ```
  - `src` : 이미지 경로 => (string, required)
  - `outline` : 이미지 경계선 절정(boolean, optional) 고정값은 `false` 이에요
  - `size` : 이미지 사이즈(string, optional) 고정값은 `medium` 이에요

*  `path` 를 사용하기 위해서 `@types/node` 의존성을 추가 했어요

* @asset 절대 경로를 위해서 `vite.config.js` `tsconfig.path.json` 파일을 수정 했어요. 

## 📷 스크린샷 (Optional)
<figure>
    <img src="https://ifh.cc/g/NFksPv.jpg">
</figure>

2023-03-21 08:45 UTC, dohun31 requested changes
유틸함수로 분리하면 style.ts 파일이 굳이 필요 없을 것 같아요.
style이라는 이름에 type, constants, function 등등 뭐가 다양해서 이것도 제대로 type, constants파일 등으로 분리해주면 좋을것같아요. 👍

2023-03-21 08:45 UTC, dohun31 commented on src/components/Image/style.ts
> +
함수에 파라미터로 `xx px`가 아니라 number를 전달하는게 더 실용적인것 같아요.

2023-03-21 08:45 UTC, dohun31 commented on src/components/Image/style.ts
> +
그리고 유틸 함수로 빼도 될것같아요.
정사각형이 아니라 width, hegiht 값을 따로 받게 하면 Image가 아니라 다른 곳에서도 해당 함수를 사용해서 width, hegiht를 만들 수 있을 것 같아요.

2023-03-28 04:21 UTC, hwinkr commented on src/components/Image/style.ts
> +
유틸함수로 빼도록 하겠습니다 ㅎ.ㅎ

2023-03-28 04:23 UTC, dohun31 commented on src/components/Image/index.tsx
> +const small = '150 px' as CSSProperties['height' | 'width'];
상수 컨벤션 맞춰서 적어주세요 :)

근데 '250 px' 이렇게 사이를 보통 띄우나요?

2023-03-28 04:23 UTC, dohun31 commented on src/components/Image/index.tsx
> +const border: CSSProperties['border'] = '3px solid black';
얘도 상수 컨벤션 맞춰주세요

2023-03-28 04:23 UTC, dohun31 commented on src/components/Image/index.tsx
> +const border: CSSProperties['border'] = '3px solid black';
얘를 따로 상수로 빼야하는 이유가 있나요?

2023-03-28 04:25 UTC, hwinkr commented on src/components/Image/index.tsx
> +const small = '150 px' as CSSProperties['height' | 'width'];
저는 이때까지 한칸씩 띄우긴 했는데, 유틸함수로 바꾸면서 같이 수정할 수 있도록 할게요. :)

2023-03-28 04:26 UTC, hwinkr commented on src/components/Image/index.tsx
> +const border: CSSProperties['border'] = '3px solid black';
딱히 뺀 이유는 없습니다. 같이 수정할게요 :)

2023-03-28 05:44 UTC, dohun31 approved these changes

2023-03-28 05:45 UTC, merged