Config/#24: @types 폴더 절대경로 설정
GDSC-PKNU-21-22/pknu-notice pull request #25
Opened 2023-03-28 07:03 UTC by hwinkr

## 🤠 개요

- Closes : #24 
- @types 폴더 절대경로 설정을 했어요

## 💫 설명

- 폴더이름은 @types 인데, 절대경로 이름은 @type 이에요. types 폴더 이름이 겹쳐서 일단 임시방편으로 이렇게 했어요
## 📷 스크린샷 (Optional)

2023-03-31 08:10 UTC, pp449 approved these changes
LGTM

2023-04-01 07:29 UTC, hwinkr commented
> LGTM

2023-04-01 07:48 UTC, pp449 requested changes

2023-04-01 08:13 UTC, hwinkr commented on tsconfig.path.json
> +      "@type/*": ["./src/@types/*"],
@types 로 하게되면 저희가 정의한 폴더가 아닌, ts 내장 폴더로 가서 타입들을 찾는 문제가 발생해서 해결방법으로 @type 으로 하기로 했습니다 ~! :)

2023-04-01 08:54 UTC, pp449 approved these changes
Good ~

2023-04-02 09:26 UTC, merged