Feat/#9: 하단 탭 구현
GDSC-PKNU-21-22/pknu-notice pull request #33
Opened 2023-04-02 09:43 UTC by pp449

## 🤠 개요
- Closes: #9 

## 💫 설명

하단에 아이콘 누르면 색이랑 URL 변경되는 기능 추가

## 📷 스크린샷 (Optional)

https://user-images.githubusercontent.com/71641127/229345030-4faf13a4-b399-4f98-9f2f-57b371f46f29.mov

2023-04-07 04:14 UTC, hwinkr requested changes
✅🙋‍♂️👍

2023-04-07 04:14 UTC, hwinkr commented on src/components/FooterTab/index.tsx
> +`;
styled.div 내부에서 사용할, 스타일과 관련있는  props 만 넘겨주면 더 괜찮지 않을까요?
```typescript
type IconContainerProps = {
  onClick: () => void;
};

```
이렇게 타입을 정의하고 styled.div 에 넘겨줬지만 스타일과 관련이 없는 타입이라서 내부에서 사용을 안하고 있기도 하고,
`onClick` 속성은 기본 div 태그에 있는걸 사용하면 더 괜찮을 것 같다는 생각이 듭니다...!

2023-04-09 10:27 UTC, pp449 commented on src/components/FooterTab/index.tsx
> +          />
앗 그걸 생각 못했네요,, 바로 수정하겠습니다

2023-05-01 06:16 UTC, hwinkr approved these changes
LGTM!

2023-05-01 06:17 UTC, merged