Feat/#23: Home 에서 사용할 Card 컴포넌트 구현
GDSC-PKNU-21-22/pknu-notice pull request #37
Opened 2023-04-05 15:07 UTC by hwinkr

## 🤠 개요

* Home 에서 사용 할 Card 컴포넌트 구현을 했어요.
* useNavigate 를 사용해서 페이지 이동이 잘 되는지에 대한 테스트 코드를 작성했어요.

### 🙋‍♂️ 추가로 작은 변경사항이 있어요.

```typescript
interface InformCardProps {
  icon: IconKind & ('school' | 'notification');
  title: string;
  path: string;
}
```
* Icon 컴포넌트에서 사용했던 `IconKind` type 을 `@types/styles/icon.ts` 로 옮겼어요.  
  * `InformCardProps` 를 정의해 줄 때, `IconKind & ('school' | 'notification');` 구문을 사용하기 위해서 import 해야해서, 여기저기서 사용하는 타입이라서 `@types` 폴더로 옮겼어요.  
 

## 💫 설명

* `InformCard` 는 컴포넌트에서 사용 할, `icon`, `title`, `path` 3개의 props 을 받아요.  
  *  호출 방식은 아래와 같아요.
```react
<InformCard icon="notification" title="공지사항" path="/announcement"/>
``` 
  

* `졸업요건` 카드 컴포넌트 테스트 하는 과정에서 일단 사용할 수 있는 'path' 인 '/announcement' 를 적용해서 테스트 했어요.  
  * 졸업요건을 클릭 했을 때, 페이지 이동을 하고 졸업요건 이미지를 보여주기로 했었는데 이에 대한 페이지 경로가 아직 없어서 일단 사용할 수 있는 `/announcement` 경로를 사용해서 테스트 했어요.
```typescript
it('졸업요건 클릭 테스트', () => {
    const icon = 'school';
    const title = '졸업요건';
    const path = 'announcement';
    const testComponent = render(
      <ThemeProvider>
        <BrowserRouter>
          <InformCard icon={icon} title={title} path={path} />,
        </BrowserRouter>
      </ThemeProvider>,
    );
```

## 📷 스크린샷 (Optional)
<figure>
    <img src="https://ifh.cc/g/MdApkX.jpg" height='200px' width='200px'>
</figure>

2023-04-06 09:22 UTC, pp449 requested changes
화이팅..!

2023-04-06 09:22 UTC, pp449 commented on src/components/Card/InformCard/index.test.tsx
> +    const testComponent = render(
ThemeProvider랑 BrowserRouter를 감싸주기보다

import { MemoryRouter } from 'react-router-dom'; 
render(<InformCard .... />, { wrapper: MemoryRouter });

로 해당 컴포넌트만 가져와서 실제 URL 이동이 아닌 가상 라우터에서 URL 이동이 되었는지 확인하면 좋을듯

2023-04-06 09:22 UTC, pp449 commented on src/components/Card/InformCard/index.test.tsx
> +    const card = testComponent.container.querySelector('div');
DOM 요소로 접근하기 보다 screen 을 이용하여 해당 컴포넌트에 접근하는 방법이 좋지 않을까유?

2023-04-06 09:22 UTC, pp449 commented on src/components/Card/InformCard/index.tsx
> +        color={icon === 'school' ? theme.text.gray : theme.text.white}
보다 생각난건데 theme도 상수여서 전부다 대문자로 하는게 좋을듯

THEME.TEXT.GRAY 처럼 수정,, 될까유,,?

2023-04-06 09:22 UTC, pp449 commented on src/components/Icon/index.tsx
> +import { IconKind } from '@type/styles/icon';
icon type 을 따로 뺀건 좋은듯 👍

2023-04-06 15:35 UTC, hwinkr commented on src/components/Card/InformCard/index.test.tsx
> +      fireEvent.click(card);
오..이건 처음 알았습니다, 적용할게요

2023-04-06 15:35 UTC, hwinkr commented on src/components/Card/InformCard/index.test.tsx
> +    const icon = 'notification';
테스트 코드에도 컨벤션 잘 적용하도록 할게요 :)

2023-04-06 15:35 UTC, hwinkr commented on src/components/Card/InformCard/index.test.tsx
폴더로 관심사 분리 했으니까 그 폴더 내부에서는 index 로 통일하는게 보기 좋을듯?!

2023-04-06 15:37 UTC, hwinkr commented on src/components/Card/InformCard/index.tsx
> +        color={icon === 'school' ? theme.text.gray : theme.text.white}
그러네.. 색깔들도 다 상수로 취급할 수 있겠네, 상수 컨벤션으로 맞춰놓으면 나머지 props, 변수들이랑 구분하기도 편할 듯?
이건 따로 이슈 파서 수정 할게요 :)

2023-04-06 15:38 UTC, hwinkr commented on src/components/Card/InformCard/index.test.tsx
> +    const testComponent = render(
가상 라우터..? 한번 알아보고 적용해보겠슴 :)

2023-04-06 17:26 UTC, pp449 commented on src/components/Card/InformCard/index.test.tsx
오키 그럼 test파일도 index.test.tsx 로 하는걸로 하쥬

2023-04-09 13:04 UTC, pp449 reviewed
궁금한점 ~

2023-04-09 13:04 UTC, pp449 commented on src/components/Card/InformCard/index.test.tsx
> +      <ThemeProvider>
ThemeProvider도 같이 렌더링하는 이유가 있을까요 ??

2023-04-09 13:04 UTC, pp449 commented on src/components/Card/InformCard/index.test.tsx
> +    waitFor(() => {
waitFor 도 사용할수 있는지 처음 알았네유

저는 
`await userEvent.click(card);`
방식도 괜찮더라고여 ㅎㅎ

2023-04-09 13:09 UTC, hwinkr commented on src/components/Card/InformCard/index.test.tsx
> +      <ThemeProvider>
같이 렌더링을 해주지 않으니까, 
```typescript
const Card = styled.div<CardProps>(({ icon, theme }) => {
  return {
    //...
    backgroundColor: icon === 'school' ? theme.background : theme.primary,
    color: icon === 'school' ? theme.text.gray : theme.text.white,
    //...
  };
});
```
`styled.div` 를 통해서 만든 `Card` 컴포넌트의 theme 을 읽을수 없다는 에러가 떠서 같이 렌더링을 해주니까 test 통과가 됐었습니다.
제가 생각 했을 때,  테스트 환경에서 `InformCard` 만 렌더링 하는 경우 `ThemeProvider` 에서 제공해주는 `theme` 을 읽을 수 없어서 생기는 문제인 것 같습니다..!

2023-04-09 13:10 UTC, hwinkr commented on src/components/Card/InformCard/index.test.tsx
> +    waitFor(() => {
저도 #33 여기 보고, await 방식이 더 괜찮은것 같아서 방금 수정 했습니다~😁

2023-04-10 06:21 UTC, pp449 requested changes
수정 다하면 code review의 Comment 로 수정했다고 글 적으면 알림이 오지 않을까요 ??

2023-04-10 06:21 UTC, pp449 commented on src/components/Card/InformCard/index.test.tsx
> +      <ThemeProvider>
상단에 theme 을 import 해와서 사용하기 때문에 props 로 theme 을 받을 필요 없어보여요

theme props 를 삭제하고 

const Card = styled.div<CardProps>(({ icon })

render(<InformCard icon={ICON} title={TITLE} path={PATH} />, {wrapper: MemoryRouter }) 로 바꾸는건 어떨까요?

2023-04-10 06:21 UTC, pp449 commented on src/components/Card/InformCard/index.tsx
> +        color={icon === 'school' ? theme.text.gray : theme.text.white}
theme이 수정되었으니까

dev 브랜치를 pull 해와서 theme 상수값들을 THEME.TEXT.GRAY 로 대문자로 변경하는게 좋을거 같아요

2023-04-10 06:34 UTC, hwinkr commented on src/components/Card/InformCard/index.test.tsx
> +      <ThemeProvider>
아 왜 위에서 불러왔다는걸 몰랐지..ThemeProvider 제거 했고, 상수 컨벤션 맞춰서 수정했습니다~

2023-04-10 07:06 UTC, pp449 approved these changes
OK

2023-04-10 10:00 UTC, merged